import csv
from collections import Counter

with open('car.csv') as csvfile:
  readcsv = csv.reader(csvfile, delimiter = ,)
  numclaims = []
  for row in readcsv:
    claims = row[3]
  
    numclaims.append(claims)
  numclaims [0] = '0'
  print (numclaims)
  x = numclaims.count(1)
  print (x)
  #res = Counter(numclaims)
  #print (res)
  #res1 = res.count("0")
  #print (res1)
 
 
# calculates the number of values in a list, A(0) = 63233, B(1) = 4333, C(2) = 271, D(3) = 18, E(4) = 2
