import xlrd
file_location = "/home/mint/project_2/private-motor-insurance-statistics-2015-appendix-3-4.xlsx"  % file location
workbook = xlrd.open_workbook(file_location) % open excel file
sheet = workbook.sheet_by_index(0)  % which sheet of excel file with the first being 0 or 1
r3_c1 = sheet.cell_value(3,1) % select the (row,coloum) to read
% sheet.nrows number of rows 
sheet.ncols number of colums
for col in range(sheet.ncols):
    print sheet.cell_value(3, col)


