import xlrd
file_location = "/home/mint/project_2/private-motor-insurance-statistics-2015-appendix-3-4.xlsx"  # file location
workbook = xlrd.open_workbook(file_location) # open excel file
sheet = workbook.sheet_by_index(0)  # which sheet of excel file with the first being 0 or 1
# r3_c1 = sheet.cell_value(r,c) # select the (row,coloum) to read
#sheet.nrows # number of rows 
#sheet.ncols # number of colums
#for col in range(sheet.ncols):
   #print sheet.cell_value(3, col)
#data = [[sheet.cell_value(r,c) for c in range(sheet.ncols)] for r in range (sheet.nrows)]

#def row_values()
  # sheet.nrows # number of rows
  # sheet.ncols # number of colums
#data = [[sheet.cell_value(r,c) for r in range(1)] for c in range (3)]  
Row_values():
  r3_c1 = sheet.cell_value(r,c) # select the (row,coloum) to read
  c = 1
  for r in rrange(3, 10):
      return r3_c1
trial_3to1 = Row_values()
print trial_3to1
